# Generated by Django 4.0.1 on 2023-12-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('altitude', models.FloatField(default=0.0)),
            ],
        ),
    ]
