# Generated by Django 4.0.1 on 2023-12-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_corrections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrover',
            name='id',
        ),
        migrations.AlterField(
            model_name='clientrover',
            name='mountPoint',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
