# Generated by Django 4.0.1 on 2023-12-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_clientrover_id_alter_clientrover_mountpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('basestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.serverbasestation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.clientrover')),
            ],
        ),
    ]
