# Generated by Django 4.0.1 on 2023-12-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_casterrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='casterrooms',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.clientrover'),
        ),
        migrations.AddField(
            model_name='casterrooms',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.serverbasestation'),
        ),
        migrations.AlterField(
            model_name='connections',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.clientrover'),
        ),
    ]
