# Generated by Django 4.0.1 on 2023-12-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_connections_channel_serverbasestation_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
