# Generated by Django 4.0.1 on 2023-12-19 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0010_casterrooms_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('altitude', models.FloatField(default=0)),
                ('previous_latitude', models.FloatField(default=0)),
                ('previous_longitude', models.FloatField(default=0)),
                ('previous_altitude', models.FloatField(default=0)),
                ('previous_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='casterrooms',
            name='client',
        ),
        migrations.RemoveField(
            model_name='casterrooms',
            name='server',
        ),
        migrations.RemoveField(
            model_name='connections',
            name='basestation',
        ),
        migrations.RemoveField(
            model_name='connections',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='connections',
            name='client',
        ),
        migrations.DeleteModel(
            name='Corrections',
        ),
        migrations.DeleteModel(
            name='CasterRooms',
        ),
        migrations.DeleteModel(
            name='ClientRover',
        ),
        migrations.DeleteModel(
            name='Connections',
        ),
        migrations.DeleteModel(
            name='ServerBaseStation',
        ),
    ]
