# Generated by Django 4.0.1 on 2023-12-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_client_name_remove_server_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
